# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - blaise.tk
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Fix
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Add
        - enhancement
    - title: Other Changes
      labels:
        - "*"
  custom:
    sections:
      - title: Important Installation Guidelines
        content: |
          ### Before You Install Applio
          Please review these essential instructions to ensure a smooth installation:

          - **File Location**: Place the Applio files in a dedicated folder on your C drive.
          - **Access Control**: Avoid placing Applio in folders that require elevated privileges.
          - **Administrator Rights**: Do not run the `run-install.bat` script with administrator privileges.
          - **Path Requirements**: Ensure the installation path is free of spaces or special characters.
          - **Security Settings**: Temporarily disable your antivirus and firewall to prevent any issues with missing dependencies during installation.

          ### Installation Steps
          1. **Download**: Get the .zip file from [this link](https://github.com/IAHispano/Applio/archive/refs/tags/{{tag_name}}.zip).
          2. **Run the Installer**: Extract the files and execute the `run-install.bat` script.
          3. **Start Applio**: Launch Applio by running the `run-applio.bat` script.

          ### Prefer a Simpler Installation?
          > [!TIP]
          > For the best experience, we highly recommend using the pre-compiled version. Compiling the code yourself may lead to instabilities.

          - **Download Compiled Version**: Get the executable from [this link](https://huggingface.co/IAHispano/Applio/tree/main/Compiled).
          - **Run Applio**: Double-click the downloaded `.exe` file, then open the `run-applio.bat` file.
      - title: What's New in This Release
        content: |
          **Full Changelog**: https://github.com/IAHispano/Applio/compare/{{previous_tag_name}}...{{tag_name}}
