name: Issues Helper

on:
  issues:
    types: [opened, edited]

jobs:
  close_incomplete_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue follows the template
        id: issue_check
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body || '';
            const requiredSections = [
              '**Bug Description**',
              '**Steps to Reproduce**',
              '**Expected Behavior**',
              '**Desktop Details:**',
              '**Additional Context**'
            ];

            const issueValid = requiredSections.every(section => issueBody.includes(section));

            return issueValid;

      - name: Comment and close the issue if it doesn't follow the template
        if: steps.issue_check.outputs.result == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Add a comment to the issue
            await github.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body: `Hi there! It seems that your issue does not follow our template guidelines.

Please edit your issue to include all required sections:

- **Bug Description**
- **Steps to Reproduce**
- **Expected Behavior**
- **Desktop Details:**
- **Additional Context**

If you need more help, feel free to join our Discord for support.

This issue will be closed automatically, but you can reopen it once it meets the requirements. Thank you!`
            });

            // Close the issue
            await github.issues.update({
              owner,
              repo,
              issue_number: issueNumber,
              state: 'closed'
            });
