name: Issue Helper

on:
  issues:
    types: [opened, edited]

jobs:
  check_issue_template:
    runs-on: ubuntu-latest
    steps:
      - name: Check Issue Template
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = context.payload.issue;
            const requiredSections = [
              '**Bug Description**',
              '**Steps to Reproduce**',
              '**Desktop Details:**',
            ];
            
            const body = issue.body;
            const missingFields = requiredSections.filter(section => !body.includes(section));
            
            if (missingFields.length > 0) {
              const message = `Thank you for your issue report. However, it appears that your issue description is missing the following required sections:\n${missingFields.map(field => `- ${field}`).join('\n')}\n\nPlease edit your issue to include all required information using our issue template. This helps us address your concern more effectively.\nIf you need assistance with the template or have any questions, please join our Discord server for support.\n\nThis issue will be closed automatically. Feel free to reopen it once you've updated it with the required information.`;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: message
              });
              
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }
