name: Pre-Compiled and Upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          .\run-install.bat
          .\env\python.exe core.py prerequisites --models "True"

      - name: Clean up unnecessary files
        run: |
          Remove-Item -Path 'LICENSE', 'run-install.bat', 'requirements.txt', '.gitignore' -Force -ErrorAction SilentlyContinue
          Remove-Item -Path '.github' -Recurse -Force -ErrorAction SilentlyContinue
      
      - name: Create ZIP file
        run: |
          powershell -Command "
          Compress-Archive -Path 'D:\a\Applio\Applio\*' -DestinationPath 'D:\a\Applio\Applio.zip'
          "

      - name: Upload to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          .\env\python.exe -c "
          import os
          from huggingface_hub import login, upload_file
          
          token = os.getenv('HF_TOKEN')
          login(token)
          repo_id = 'vidalnt/nothing'
          repo_file_path = '../Applio.zip'
          
          upload_file(
          path_or_fileobj=repo_file_path,
          path_in_repo='Applio.zip',
          repo_id=repo_id,
          token=token)
          "
