name: Scan, Install, and Compare

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Scan and create initial index
        run: |
          python -c "
          import csv
          import os
          def scan_and_write(base_path, output_file):
              with open(output_file, 'w', newline='') as f:
                  writer = csv.writer(f)
                  for dirpath, dirs, files in os.walk(base_path):
                      for filename in files:
                          fname = os.path.join(dirpath, filename)
                          try:
                              mtime = os.path.getmtime(fname)
                              writer.writerow([fname, mtime])
                          except Exception as e:
                              print(f'Skipping irrelevant nonexistent file {fname}: {str(e)}')
              print(f'Finished recording filesystem timestamps to {output_file}.')
          
          scan_and_write(\"/opt/pipx/venvs/ansible-core/lib/python3.10/site-packages\", \"./usr_files.csv\")"
          
      - name: Install pypresence
        run: |
          pip install pypresence
          
      - name: Scan and create new index
        run: |
          python -c "
          import csv
          import os
          def scan_and_write(base_path, output_file):
              with open(output_file, 'w', newline='') as f:
                  writer = csv.writer(f)
                  for dirpath, dirs, files in os.walk(base_path):
                      for filename in files:
                          fname = os.path.join(dirpath, filename)
                          try:
                              mtime = os.path.getmtime(fname)
                              writer.writerow([fname, mtime])
                          except Exception as e:
                              print(f'Skipping irrelevant nonexistent file {fname}: {str(e)}')
              print(f'Finished recording filesystem timestamps to {output_file}.')
          
          scan_and_write(\"/opt/pipx/venvs/ansible-core/lib/python3.10/site-packages\", \"./usr_files_new.csv\")"
          
      - name: Compare files and display changes
        run: |
          python -c "
          import csv

          def compare_files(old_file, new_file):
              old_files = {}
              new_files = {}

              with open(old_file, 'r') as f:
                  reader = csv.reader(f)
                  old_files = {rows[0]: rows[1] for rows in reader}

              with open(new_file, 'r') as f:
                  reader = csv.reader(f)
                  new_files = {rows[0]: rows[1] for rows in reader}

              removed_files = old_files.keys() - new_files.keys()
              added_files = new_files.keys() - old_files.keys()
              unchanged_files = old_files.keys() & new_files.keys()

              changed_files = {f for f in unchanged_files if old_files[f] != new_files[f]}

              for file in removed_files:
                  print(f'File has been removed: {file}')

              for file in changed_files:
                  print(f'File has been updated: {file}')

              return list(added_files) + list(changed_files)

          changed_files = compare_files('/content/usr_files.csv', '/content/usr_files_new.csv')
          print('Changed files:')
          for file in changed_files:
              print(file)
          "
