name: Cache Python Dependencies

on:
  workflow_dispatch:

jobs:
  Kaggle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Free up space on runner
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Read version from config.json
        id: get-version
        run: |
          version=$(jq -r '.version' assets/config.json)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Install uv and create virtual environment
        run: |
          sudo apt-get install -y pigz
          sudo apt-get install -y pv
          pip install uv huggingface_hub
          uv venv .venv --python 3.10.12
          uv pip install -r requirements.txt
          uv pip install https://github.com/Vidalnt/imjoy-elfinder.git
          uv pip uninstall torch torchvision torchaudio
          . .venv/bin/activate
          python -m ensurepip
          python -m pip install "pip<24.1"
          python -m pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu121
          deactivate
          wget https://huggingface.co/vidalnt/env/resolve/main/bin_kaggle.tar.gz?download=true -O bin_kaggle.tar.gz
          tar -xzf bin_kaggle.tar.gz
          cp -r bin/* .venv/bin/
          rm -rf bin
          rm bin_kaggle.tar.gz
          rm -f .venv/pyvenv.cfg
          rm -f .venv/bin/activate
          rm -f .venv/bin/activate.bat
          rm -f .venv/bin/activate.csh
          rm -f .venv/bin/activate.fish
          rm -f .venv/bin/activate.nu
          rm -f .venv/bin/activate.ps1
          rm -f .venv/bin/activate_this.py
          rm -f .venv/bin/deactivate.bat
          rm -f .venv/bin/pydoc.bat
          rm -f .venv/bin/python
          rm -f .venv/bin/python3
          rm -f .venv/bin/python3.10
      
      - name: Create TAR Env
        run: |
          tar --use-compress-program="pigz --best --recursive | pv" -cvf KaggleV2.tar.gz .venv

      - name: Upload Kaggle Env
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          import os
          from huggingface_hub import login, upload_file
            
          token = os.getenv('HF_TOKEN')
          login(token)
          repo_id = 'vidalnt/nothing'
          repo_file_path = 'KaggleV2.tar.gz'
            
          upload_file(
          path_or_fileobj=repo_file_path,
          path_in_repo=f'Enviroment/Kaggle/{repo_file_path}',
          repo_id=repo_id,
          token=token)
          "