name: Pre-Compiled and Upload
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@main
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          .\run-install.bat
          .\env\python.exe core.py prerequisites --models "True"
      
      - name: Create ZIP file
        run: |
          .\env\python.exe -c "
import os
import zipfile
from tqdm import tqdm

def zip_dir(zip_filename, dir_to_zip):
    with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(dir_to_zip):
            for file in tqdm(files, desc=f'Compressing {dir_to_zip}', unit='file'):
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, start=dir_to_zip)
                zipf.write(file_path, arcname)

zip_dir('../Applio.zip', '../Applio')
          "

      - name: Upload to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          .\env\python.exe -c "
import os
from huggingface_hub import login, upload_file

token = os.getenv('HF_TOKEN')
login(token)

repo_id = 'vidalnt/nothing'
repo_file_path = '../Applio.zip'

upload_file(
    path_or_fileobj=repo_file_path,
    path_in_repo='Applio.zip',
    repo_id=repo_id,
    token=token
)
          "